#!/usr/bin/env python3
"""Regenerate the PowerGridModel (PGM) benchmark golden data for Literal PMDSE.

Reads PGM's own state-estimation validation cases, runs PGM, and emits

    golden.json          - machine-readable network + sensors + PGM node voltages
    pgm_cases_data.jl    - the `const PGM_CASES = [...]` block embedded by
                           test/literal/pgm_cases.jl

Usage
-----
    pip install power-grid-model numpy
    python3 generate_golden.py /path/to/power-grid-model

If the path is omitted, the env var PGM_REPO or ../../../../power-grid-model is
tried.  Only the symmetric (single-phase) cases below are exported; they are the
ones the literal estimator is benchmarked against (the four-wire generality is
covered separately by the explicit-neutral feeder tests).
"""
import json, os, sys
import numpy as np
from power_grid_model import PowerGridModel, CalculationMethod
from power_grid_model.utils import json_deserialize

# (julia name, PGM folder under tests/data/state_estimation, methods)
CASES = [
    ("single_node",       "single-node-source-sym-voltage-sensor", ["il", "nr"]),
    ("os1_2msr",          "1os2msr",                                ["il", "nr"]),
    ("os1_2msr_no_angle", "1os2msr-no-angle",                       ["il", "nr"]),
    ("single_line_load",  "single-line-load-il",                    ["il"]),
]
METH = {"il": CalculationMethod.iterative_linear, "nr": CalculationMethod.newton_raphson}
MTERM = {0: "branch_from", 1: "branch_to", 2: "source", 4: "load", 5: "gen"}
FREQ = 50.0


def pgm_repo():
    if len(sys.argv) > 1:
        return sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    return os.environ.get("PGM_REPO", os.path.join(here, "..", "..", "..", "..", "power-grid-model"))


def case_dict(base, name, folder, methods):
    with open(f"{base}/tests/data/state_estimation/{folder}/input.json") as f:
        inp = json_deserialize(f.read())
    d = dict(name=name, folder=folder, methods=methods)
    d["nodes"] = [dict(id=int(n["id"]), u_rated=float(n["u_rated"])) for n in inp["node"]]
    d["lines"] = [dict(id=int(l["id"]), f=int(l["from_node"]), t=int(l["to_node"]),
                       r1=float(l["r1"]), x1=float(l["x1"]), c1=float(l["c1"]), tan1=float(l["tan1"]),
                       fs=int(l["from_status"]), ts=int(l["to_status"])) for l in inp.get("line", [])]
    d["source"] = dict(id=int(inp["source"][0]["id"]), node=int(inp["source"][0]["node"]))
    d["loads"] = [dict(id=int(l["id"]), node=int(l["node"])) for l in inp.get("sym_load", [])]
    appnode = {int(inp["source"][0]["id"]): ("source", int(inp["source"][0]["node"]))}
    for l in inp.get("sym_load", []):
        appnode[int(l["id"])] = ("load", int(l["node"]))
    d["vsensors"] = []
    for s in inp.get("sym_voltage_sensor", []):
        ang = float(s["u_angle_measured"]); has = not np.isnan(ang)
        d["vsensors"].append(dict(node=int(s["measured_object"]), u=float(s["u_measured"]),
                                  ang=(ang if has else None), sigma=float(s["u_sigma"])))
    d["psensors"] = []
    for s in inp.get("sym_power_sensor", []):
        tt = int(s["measured_terminal_type"]); kind = MTERM[tt]
        e = dict(kind=kind, p=float(s["p_measured"]), q=float(s["q_measured"]), sigma=float(s["power_sigma"]))
        if kind in ("branch_from", "branch_to"):
            e["branch"] = int(s["measured_object"])
        else:
            e["node"] = appnode[int(s["measured_object"])][1]; e["app"] = appnode[int(s["measured_object"])][0]
        d["psensors"].append(e)
    model = PowerGridModel(inp, system_frequency=FREQ)
    exp = {}
    for m in methods:
        out = model.calculate_state_estimation(symmetric=True, error_tolerance=1e-12,
                                               max_iterations=100, calculation_method=METH[m])
        nd = out["node"]
        nodes = {int(r["id"]): dict(u=float(r["u"]),
                                    u_angle=float(r["u_angle"]) if "u_angle" in nd.dtype.names else 0.0) for r in nd}
        lines = {}
        if "line" in out:
            for r in out["line"]:
                lines[int(r["id"])] = dict(p_from=float(r["p_from"]), q_from=float(r["q_from"]),
                                           p_to=float(r["p_to"]), q_to=float(r["q_to"]))
        exp[m] = dict(nodes=nodes, lines=lines)
    d["expected"] = exp
    return d


def emit_julia(cases):
    jn = lambda x: repr(float(x))
    ja = lambda a: "nothing" if a is None else repr(float(a))
    o = ["# AUTO-GENERATED by test/literal/pgm/generate_golden.py — DO NOT EDIT BY HAND.",
         "# Golden state-estimation cases exported from power-grid-model (PGM),",
         "# tests/data/state_estimation/*.  PGM-computed node voltages per method.",
         "", "const PGM_CASES = ["]
    for c in cases:
        o.append("    (")
        o.append(f"        name = {json.dumps(c['name'])},")
        o.append(f"        folder = {json.dumps(c['folder'])},")
        o.append("        methods = [" + ", ".join(":" + m for m in c["methods"]) + "],")
        o.append("        nodes = [" + ", ".join(f"(id={n['id']}, u_rated={jn(n['u_rated'])})" for n in c["nodes"]) + "],")
        o.append("        lines = [" + ", ".join(
            f"(id={l['id']}, f={l['f']}, t={l['t']}, r1={jn(l['r1'])}, x1={jn(l['x1'])}, c1={jn(l['c1'])}, tan1={jn(l['tan1'])}, fs={l['fs']}, ts={l['ts']})"
            for l in c["lines"]) + "],")
        o.append(f"        source = (id={c['source']['id']}, node={c['source']['node']}),")
        o.append("        loads = [" + ", ".join(f"(id={l['id']}, node={l['node']})" for l in c["loads"]) + "],")
        o.append("        vsensors = [" + ", ".join(
            f"(node={v['node']}, u={jn(v['u'])}, ang={ja(v['ang'])}, sigma={jn(v['sigma'])})" for v in c["vsensors"]) + "],")
        ps = []
        for p in c["psensors"]:
            loc = f"branch={p['branch']}" if "branch" in p else f"node={p['node']}, app={json.dumps(p['app'])}"
            ps.append(f"(kind={json.dumps(p['kind'])}, {loc}, p={jn(p['p'])}, q={jn(p['q'])}, sigma={jn(p['sigma'])})")
        o.append("        psensors = [" + ", ".join(ps) + "],")
        o.append("        expected = Dict(")
        for m, e in c["expected"].items():
            ne = ", ".join(f"{nid} => (u={jn(v['u'])}, u_angle={jn(v['u_angle'])})" for nid, v in e["nodes"].items())
            le = ", ".join(f"{lid} => (p_from={jn(v['p_from'])}, q_from={jn(v['q_from'])}, p_to={jn(v['p_to'])}, q_to={jn(v['q_to'])})"
                           for lid, v in e["lines"].items())
            o.append(f"            {json.dumps(m)} => (nodes = Dict({ne}), lines = Dict({le})),")
        o.append("        ),")
        o.append("    ),")
    o.append("]")
    return "\n".join(o) + "\n"


def main():
    base = pgm_repo()
    if not os.path.isdir(f"{base}/tests/data/state_estimation"):
        sys.exit(f"power-grid-model repo not found at {base!r}; pass its path as argv[1] or set PGM_REPO")
    cases = [case_dict(base, *c) for c in CASES]
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "golden.json"), "w") as f:
        json.dump(cases, f, indent=1)
    with open(os.path.join(here, "pgm_cases_data.jl"), "w") as f:
        f.write(emit_julia(cases))
    print(f"wrote golden.json and pgm_cases_data.jl for {len(cases)} cases from {base}")


if __name__ == "__main__":
    main()
