# AUTO-GENERATED by test/literal/pgm/generate_golden.py — DO NOT EDIT BY HAND.
# Golden state-estimation cases exported from power-grid-model (PGM),
# tests/data/state_estimation/*.  PGM-computed node voltages per method.

const PGM_CASES = [
    (
        name = "single_node",
        folder = "single-node-source-sym-voltage-sensor",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10000.0)],
        lines = [],
        source = (id=2, node=1),
        loads = [],
        vsensors = [(node=1, u=12345.0, ang=0.1, sigma=100.0)],
        psensors = [],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=12345.0, u_angle=0.1)), lines = Dict()),
            "nr" => (nodes = Dict(1 => (u=12345.0, u_angle=0.09999999999999999)), lines = Dict()),
        ),
    ),
    (
        name = "os1_2msr",
        folder = "1os2msr",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10500.0), (id=2, u_rated=10500.0), (id=3, u_rated=10500.0)],
        lines = [(id=4, f=1, t=2, r1=0.11, x1=0.12, c1=4.1380285203892784e-05, tan1=0.1076923076923077, fs=1, ts=1), (id=5, f=2, t=3, r1=0.15, x1=0.16, c1=5.411268065124442e-05, tan1=0.10588235294117646, fs=1, ts=1)],
        source = (id=6, node=1),
        loads = [(id=7, node=2), (id=8, node=3)],
        vsensors = [(node=1, u=10751.072595758282, ang=-0.013054638926306409, sigma=105.0), (node=2, u=10752.698591183394, ang=-0.01763734945972652, sigma=105.0), (node=3, u=10748.320749959701, ang=-0.02018233075947404, sigma=100.0)],
        psensors = [(kind="branch_from", branch=4, p=2412359.2976399013, q=-3024028.886598367, sigma=37916.0), (kind="branch_to", branch=4, p=-2000000.0, q=1000000.0, sigma=1000000000000000.0), (kind="branch_from", branch=5, p=1230426.390004009, q=-1742195.1033582848, sigma=20878.0), (kind="branch_to", branch=5, p=-1019999.9999999485, q=-219999.99999999927, sigma=10435.0), (kind="source", node=1, app="source", p=2412359.297639887, q=-3024028.8865982923, sigma=38009.0), (kind="load", node=2, app="load", p=1010000.0, q=210000.0, sigma=10316.0), (kind="load", node=3, app="load", p=1020000.0, q=220000.0, sigma=10435.0)],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=10751.072595669397, u_angle=-0.01305463892705287), 2 => (u=10752.698591094362, u_angle=-0.017637349460495298), 3 => (u=10748.32074987062, u_angle=-0.020182330760257754)), lines = Dict(4 => (p_from=2412359.297617528, q_from=-3024028.8865525783, p_to=-2240426.3899840107, q_to=1532195.1033373913), 5 => (p_from=1230426.389992248, q_from=-1742195.1033316434, p_to=-1019999.9999917165, q_to=-219999.99999405813))),
            "nr" => (nodes = Dict(1 => (u=10751.072595758176, u_angle=-0.013054638926306369), 2 => (u=10752.698591183289, u_angle=-0.01763734945972652), 3 => (u=10748.3207499596, u_angle=-0.020182330759474076)), lines = Dict(4 => (p_from=2412359.2976397616, q_from=-3024028.886598335, p_to=-2240426.390003599, q_to=1532195.1033583526), 5 => (p_from=1230426.3900039378, q_from=-1742195.1033583248, p_to=-1019999.9999998793, q_to=-219999.99999994013))),
        ),
    ),
    (
        name = "os1_2msr_no_angle",
        folder = "1os2msr-no-angle",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10500.0), (id=2, u_rated=10500.0), (id=3, u_rated=10500.0)],
        lines = [(id=4, f=1, t=2, r1=0.11, x1=0.12, c1=4.1380285203892784e-05, tan1=0.1076923076923077, fs=1, ts=1), (id=5, f=2, t=3, r1=0.15, x1=0.16, c1=5.411268065124442e-05, tan1=0.10588235294117646, fs=1, ts=1)],
        source = (id=6, node=1),
        loads = [(id=7, node=2), (id=8, node=3)],
        vsensors = [(node=1, u=10751.072595758282, ang=nothing, sigma=105.0), (node=2, u=10752.698591183394, ang=nothing, sigma=105.0), (node=3, u=10748.320749959701, ang=nothing, sigma=100.0)],
        psensors = [(kind="branch_from", branch=4, p=2412359.2976399013, q=-3024028.886598367, sigma=37916.0), (kind="branch_to", branch=4, p=-2240426.3900036793, q=1532195.1033583684, sigma=26809.0), (kind="branch_from", branch=5, p=1230426.390004009, q=-1742195.1033582848, sigma=20878.0), (kind="branch_to", branch=5, p=-1019999.9999999485, q=-219999.99999999927, sigma=10435.0), (kind="source", node=1, app="source", p=2412359.297639887, q=-3024028.8865982923, sigma=38009.0), (kind="load", node=2, app="load", p=1010000.0, q=210000.0, sigma=10316.0), (kind="load", node=3, app="load", p=1020000.0, q=220000.0, sigma=10435.0)],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=10751.072595583171, u_angle=0.0), 2 => (u=10752.698591008038, u_angle=-0.004582710533466773), 3 => (u=10748.32074978426, u_angle=-0.007127691833244886)), lines = Dict(4 => (p_from=2412359.2975955657, q_from=-3024028.886511328, p_to=-2240426.3899647417, q_to=1532195.103320241), 5 => (p_from=1230426.3899807737, q_from=-1742195.1033068383, p_to=-1019999.9999835168, q_to=-219999.99998724568))),
            "nr" => (nodes = Dict(1 => (u=10751.072595758145, u_angle=0.0), 2 => (u=10752.69859118326, u_angle=-0.0045827105334202535), 3 => (u=10748.32074995957, u_angle=-0.007127691833167822)), lines = Dict(4 => (p_from=2412359.297639833, q_from=-3024028.886598318, p_to=-2240426.390003647, q_to=1532195.1033584457), 5 => (p_from=1230426.3900038258, q_from=-1742195.1033584112, p_to=-1019999.9999998506, q_to=-219999.99999981755))),
        ),
    ),
    (
        name = "single_line_load",
        folder = "single-line-load-il",
        methods = [:il],
        nodes = [(id=11, u_rated=10500.0), (id=12, u_rated=10500.0)],
        lines = [(id=21, f=11, t=12, r1=0.1, x1=0.0, c1=0.0, tan1=0.0, fs=1, ts=1)],
        source = (id=41, node=11),
        loads = [(id=31, node=12)],
        vsensors = [(node=11, u=10500.0, ang=nothing, sigma=105.0)],
        psensors = [(kind="branch_from", branch=21, p=1000000.0, q=0.0, sigma=1000.0), (kind="load", node=12, app="load", p=2000000.0, q=0.0, sigma=1000.0), (kind="load", node=12, app="load", p=2000000.0, q=0.0, sigma=1e+200)],
        expected = Dict(
            "il" => (nodes = Dict(11 => (u=10499.999990211563, u_angle=0.0), 12 => (u=10485.70128888785, u_angle=0.0)), lines = Dict(21 => (p_from=1501363.6375900682, q_from=0.0, p_to=-1499319.1089946209, q_to=-0.0))),
        ),
    ),
]
