################################################################################
#  PowerGridModel (PGM) benchmark cases for the Literal PMDSE PGM solve options. #
#                                                                              #
#  Each entry is a PGM symmetric (single-phase positive-sequence) state-         #
#  estimation case taken verbatim from                                          #
#      power-grid-model/tests/data/state_estimation/<folder>/                   #
#  together with the node voltages PGM computes for each calculation method.    #
#  `build_pgm_math` turns the PGM network into the *same* PMD mathematical data  #
#  dictionary the package consumes (per-unit, V_base = u_rated, S_base = 1e6 =   #
#  PGM `base_power_3p`); `build_pgm_meas!` writes `data["meas"]` using the        #
#  package measurement vocabulary.  The single-phase PGM network is the special  #
#  case of the four-wire literal model with one conductor per bus and no neutral.#
#                                                                              #
#  Regenerate the golden numbers (PGM_CASES below) with                         #
#      python3 test/literal/pgm/generate_golden.py            (needs PGM + numpy)#
#  then paste test/literal/pgm/pgm_cases_data.jl in place of the block below.    #
################################################################################

import Distributions as _DST
import PowerModelsDistribution as _PMD

const PGM_FREQ  = 50.0
const PGM_SBASE = 1.0e6        # PGM common/base_power_3p (symmetric calculation)

# AUTO-GENERATED by test/literal/pgm/generate_golden.py — DO NOT EDIT BY HAND.
# Golden state-estimation cases exported from power-grid-model (PGM) v1.12,
# tests/data/state_estimation/*.  Each case carries the PGM network + sensors and
# the PGM-computed node voltages (per calculation method) used as the benchmark.

const PGM_CASES = [
    (
        name = "single_node",
        folder = "single-node-source-sym-voltage-sensor",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10000.0)],
        lines = [],
        source = (id=2, node=1),
        loads = [],
        vsensors = [(node=1, u=12345.0, ang=0.1, sigma=100.0)],
        psensors = [],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=12345.0, u_angle=0.1)), lines = Dict()),
            "nr" => (nodes = Dict(1 => (u=12345.0, u_angle=0.09999999999999999)), lines = Dict()),
        ),
    ),
    (
        name = "os1_2msr",
        folder = "1os2msr",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10500.0), (id=2, u_rated=10500.0), (id=3, u_rated=10500.0)],
        lines = [(id=4, f=1, t=2, r1=0.11, x1=0.12, c1=4.1380285203892784e-05, tan1=0.1076923076923077, fs=1, ts=1), (id=5, f=2, t=3, r1=0.15, x1=0.16, c1=5.411268065124442e-05, tan1=0.10588235294117646, fs=1, ts=1)],
        source = (id=6, node=1),
        loads = [(id=7, node=2), (id=8, node=3)],
        vsensors = [(node=1, u=10751.072595758282, ang=-0.013054638926306409, sigma=105.0), (node=2, u=10752.698591183394, ang=-0.01763734945972652, sigma=105.0), (node=3, u=10748.320749959701, ang=-0.02018233075947404, sigma=100.0)],
        psensors = [(kind="branch_from", branch=4, p=2412359.2976399013, q=-3024028.886598367, sigma=37916.0), (kind="branch_to", branch=4, p=-2000000.0, q=1000000.0, sigma=1000000000000000.0), (kind="branch_from", branch=5, p=1230426.390004009, q=-1742195.1033582848, sigma=20878.0), (kind="branch_to", branch=5, p=-1019999.9999999485, q=-219999.99999999927, sigma=10435.0), (kind="source", node=1, app="source", p=2412359.297639887, q=-3024028.8865982923, sigma=38009.0), (kind="load", node=2, app="load", p=1010000.0, q=210000.0, sigma=10316.0), (kind="load", node=3, app="load", p=1020000.0, q=220000.0, sigma=10435.0)],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=10751.072595669397, u_angle=-0.01305463892705287), 2 => (u=10752.698591094362, u_angle=-0.017637349460495298), 3 => (u=10748.32074987062, u_angle=-0.020182330760257754)), lines = Dict(4 => (p_from=2412359.297617528, q_from=-3024028.8865525783, p_to=-2240426.3899840107, q_to=1532195.1033373913), 5 => (p_from=1230426.389992248, q_from=-1742195.1033316434, p_to=-1019999.9999917165, q_to=-219999.99999405813))),
            "nr" => (nodes = Dict(1 => (u=10751.072595758176, u_angle=-0.013054638926306369), 2 => (u=10752.698591183289, u_angle=-0.01763734945972652), 3 => (u=10748.3207499596, u_angle=-0.020182330759474076)), lines = Dict(4 => (p_from=2412359.2976397616, q_from=-3024028.886598335, p_to=-2240426.390003599, q_to=1532195.1033583526), 5 => (p_from=1230426.3900039378, q_from=-1742195.1033583248, p_to=-1019999.9999998793, q_to=-219999.99999994013))),
        ),
    ),
    (
        name = "os1_2msr_no_angle",
        folder = "1os2msr-no-angle",
        methods = [:il, :nr],
        nodes = [(id=1, u_rated=10500.0), (id=2, u_rated=10500.0), (id=3, u_rated=10500.0)],
        lines = [(id=4, f=1, t=2, r1=0.11, x1=0.12, c1=4.1380285203892784e-05, tan1=0.1076923076923077, fs=1, ts=1), (id=5, f=2, t=3, r1=0.15, x1=0.16, c1=5.411268065124442e-05, tan1=0.10588235294117646, fs=1, ts=1)],
        source = (id=6, node=1),
        loads = [(id=7, node=2), (id=8, node=3)],
        vsensors = [(node=1, u=10751.072595758282, ang=nothing, sigma=105.0), (node=2, u=10752.698591183394, ang=nothing, sigma=105.0), (node=3, u=10748.320749959701, ang=nothing, sigma=100.0)],
        psensors = [(kind="branch_from", branch=4, p=2412359.2976399013, q=-3024028.886598367, sigma=37916.0), (kind="branch_to", branch=4, p=-2240426.3900036793, q=1532195.1033583684, sigma=26809.0), (kind="branch_from", branch=5, p=1230426.390004009, q=-1742195.1033582848, sigma=20878.0), (kind="branch_to", branch=5, p=-1019999.9999999485, q=-219999.99999999927, sigma=10435.0), (kind="source", node=1, app="source", p=2412359.297639887, q=-3024028.8865982923, sigma=38009.0), (kind="load", node=2, app="load", p=1010000.0, q=210000.0, sigma=10316.0), (kind="load", node=3, app="load", p=1020000.0, q=220000.0, sigma=10435.0)],
        expected = Dict(
            "il" => (nodes = Dict(1 => (u=10751.072595583171, u_angle=0.0), 2 => (u=10752.698591008038, u_angle=-0.004582710533466773), 3 => (u=10748.32074978426, u_angle=-0.007127691833244886)), lines = Dict(4 => (p_from=2412359.2975955657, q_from=-3024028.886511328, p_to=-2240426.3899647417, q_to=1532195.103320241), 5 => (p_from=1230426.3899807737, q_from=-1742195.1033068383, p_to=-1019999.9999835168, q_to=-219999.99998724568))),
            "nr" => (nodes = Dict(1 => (u=10751.072595758145, u_angle=0.0), 2 => (u=10752.69859118326, u_angle=-0.0045827105334202535), 3 => (u=10748.32074995957, u_angle=-0.007127691833167822)), lines = Dict(4 => (p_from=2412359.297639833, q_from=-3024028.886598318, p_to=-2240426.390003647, q_to=1532195.1033584457), 5 => (p_from=1230426.3900038258, q_from=-1742195.1033584112, p_to=-1019999.9999998506, q_to=-219999.99999981755))),
        ),
    ),
    (
        name = "single_line_load",
        folder = "single-line-load-il",
        methods = [:il],
        nodes = [(id=11, u_rated=10500.0), (id=12, u_rated=10500.0)],
        lines = [(id=21, f=11, t=12, r1=0.1, x1=0.0, c1=0.0, tan1=0.0, fs=1, ts=1)],
        source = (id=41, node=11),
        loads = [(id=31, node=12)],
        vsensors = [(node=11, u=10500.0, ang=nothing, sigma=105.0)],
        psensors = [(kind="branch_from", branch=21, p=1000000.0, q=0.0, sigma=1000.0), (kind="load", node=12, app="load", p=2000000.0, q=0.0, sigma=1000.0), (kind="load", node=12, app="load", p=2000000.0, q=0.0, sigma=1e+200)],
        expected = Dict(
            "il" => (nodes = Dict(11 => (u=10499.999990211563, u_angle=0.0), 12 => (u=10485.70128888785, u_angle=0.0)), lines = Dict(21 => (p_from=1501363.6375900682, q_from=0.0, p_to=-1499319.1089946209, q_to=-0.0))),
        ),
    ),
]

# ---------------------------------------------------------------------------
#  PGM network  ->  PMD mathematical data dictionary (per-unit)
# ---------------------------------------------------------------------------

"per-unit PMD `data_math` dict equivalent to a PGM symmetric case (1 conductor)"
function build_pgm_math(case)
    sbase = PGM_SBASE
    vbase = Dict(n.id => n.u_rated for n in case.nodes)
    ω = 2π * PGM_FREQ
    busd = Dict{String,Any}(); brd = Dict{String,Any}()
    loadd = Dict{String,Any}(); gend = Dict{String,Any}()

    for n in case.nodes
        bt = n.id == case.source.node ? 3 : 1
        busd[string(n.id)] = Dict{String,Any}(
            "index" => n.id, "bus_i" => n.id, "bus_type" => bt,
            "terminals" => [1], "grounded" => Bool[false],
            "vbase" => n.u_rated, "vmin" => [0.0], "vmax" => [Inf],
            "vr_start" => [1.0], "vi_start" => [0.0])
    end
    for l in case.lines
        zb = vbase[l.f]^2 / sbase                 # both ends share u_rated here
        b1 = ω * l.c1; g1 = l.tan1 * b1
        gsh = (g1 * zb) / 2; bsh = (b1 * zb) / 2  # π-model, half each end
        brd[string(l.id)] = Dict{String,Any}(
            "index" => l.id, "f_bus" => l.f, "t_bus" => l.t,
            "f_connections" => [1], "t_connections" => [1],
            "br_r" => reshape([l.r1 / zb], 1, 1), "br_x" => reshape([l.x1 / zb], 1, 1),
            "g_fr" => reshape([gsh], 1, 1), "b_fr" => reshape([bsh], 1, 1),
            "g_to" => reshape([gsh], 1, 1), "b_to" => reshape([bsh], 1, 1),
            "br_status" => (l.fs == 1 && l.ts == 1) ? 1 : 0)
    end
    # PGM source acts like a generator (defines where injection is allowed)
    gend[string(case.source.id)] = Dict{String,Any}(
        "index" => case.source.id, "gen_bus" => case.source.node,
        "connections" => [1], "configuration" => _PMD.WYE)
    for ld in case.loads
        loadd[string(ld.id)] = Dict{String,Any}(
            "index" => ld.id, "load_bus" => ld.node, "connections" => [1],
            "configuration" => _PMD.WYE, "pd" => [0.0], "qd" => [0.0],
            "model" => _PMD.POWER, "status" => 1)
    end
    return Dict{String,Any}("bus" => busd, "branch" => brd, "load" => loadd, "gen" => gend,
                            "shunt" => Dict{String,Any}(), "settings" => Dict{String,Any}("sbase" => sbase),
                            "per_unit" => true)
end

"map an appliance node id to its PGM source/load math id for this case"
function _pgm_app_id(case, node, app)
    app == "source" && return case.source.id
    for ld in case.loads
        ld.node == node && return ld.id
    end
    error("PGM case $(case.name): no $(app) appliance at node $(node)")
end

"write `data[\"meas\"]` (per-unit) from the PGM sensors, in package vocabulary"
function build_pgm_meas!(math, case)
    sbase = PGM_SBASE
    vbase = Dict(n.id => n.u_rated for n in case.nodes)
    M = Dict{String,Any}(); k = 0
    add(d) = (k += 1; M[string(k)] = d)
    N(μ, σ) = _DST.Normal(μ, σ)

    for v in case.vsensors
        vb = vbase[v.node]
        if v.ang === nothing                       # magnitude only
            add(Dict{String,Any}("cmp" => :bus, "cmp_id" => v.node, "var" => :vm,
                                 "dst" => [N(v.u / vb, v.sigma / vb)]))
        else                                       # voltage phasor -> vr & vi
            add(Dict{String,Any}("cmp" => :bus, "cmp_id" => v.node, "var" => :vr,
                                 "dst" => [N(v.u * cos(v.ang) / vb, v.sigma / vb)]))
            add(Dict{String,Any}("cmp" => :bus, "cmp_id" => v.node, "var" => :vi,
                                 "dst" => [N(v.u * sin(v.ang) / vb, v.sigma / vb)]))
        end
    end
    for p in case.psensors
        if p.kind in ("branch_from", "branch_to")
            side = p.kind == "branch_from" ? :from : :to
            add(Dict{String,Any}("cmp" => :branch, "cmp_id" => p.branch, "var" => :p, "side" => side,
                                 "dst" => [N(p.p / sbase, p.sigma / sbase)]))
            add(Dict{String,Any}("cmp" => :branch, "cmp_id" => p.branch, "var" => :q, "side" => side,
                                 "dst" => [N(p.q / sbase, p.sigma / sbase)]))
        else                                       # source / load / gen injection
            isgen = p.app in ("source", "gen")
            cmp = isgen ? :gen : :load
            aid = _pgm_app_id(case, p.node, p.app)
            pv, qv = isgen ? (:pg, :qg) : (:pd, :qd)
            add(Dict{String,Any}("cmp" => cmp, "cmp_id" => aid, "var" => pv,
                                 "dst" => [N(p.p / sbase, p.sigma / sbase)]))
            add(Dict{String,Any}("cmp" => cmp, "cmp_id" => aid, "var" => qv,
                                 "dst" => [N(p.q / sbase, p.sigma / sbase)]))
        end
    end
    math["meas"] = M
    return math
end

"complex node voltage (SI volts) of a literal result for PGM node id `nid`"
function pgm_result_voltage(case, res, nid)
    b = res.solution["bus"][string(nid)]
    vbase = first(n.u_rated for n in case.nodes if n.id == nid)
    return (b["vr"][1] + im * b["vi"][1]) * vbase
end
